import mongoose from "mongoose";
import dotenv from "dotenv";
import Item from "../models/itemModel.js";

// Load environment variables
dotenv.config();

// Generate 200 diverse grocery products
const generateProducts = () => {
    const products = [];

    // Fruits
    const fruits = [
        {
            name: "apple",
            price: 0.5,
            calories: 52,
            protein: 0.3,
            carbs: 14,
            fat: 0.2,
        },
        {
            name: "banana",
            price: 0.3,
            calories: 96,
            protein: 1.3,
            carbs: 27,
            fat: 0.3,
        },
        {
            name: "orange",
            price: 0.4,
            calories: 47,
            protein: 0.9,
            carbs: 12,
            fat: 0.1,
        },
        {
            name: "strawberry",
            price: 2.5,
            calories: 32,
            protein: 0.7,
            carbs: 8,
            fat: 0.3,
        },
        {
            name: "blueberry",
            price: 3.0,
            calories: 57,
            protein: 0.7,
            carbs: 14,
            fat: 0.3,
        },
        {
            name: "grape",
            price: 1.8,
            calories: 62,
            protein: 0.6,
            carbs: 16,
            fat: 0.2,
        },
        {
            name: "pineapple",
            price: 2.0,
            calories: 50,
            protein: 0.5,
            carbs: 13,
            fat: 0.1,
        },
        {
            name: "mango",
            price: 1.5,
            calories: 60,
            protein: 0.8,
            carbs: 15,
            fat: 0.4,
        },
        {
            name: "peach",
            price: 0.8,
            calories: 39,
            protein: 0.9,
            carbs: 10,
            fat: 0.3,
        },
        {
            name: "pear",
            price: 0.7,
            calories: 57,
            protein: 0.4,
            carbs: 15,
            fat: 0.1,
        },
        {
            name: "kiwi",
            price: 0.6,
            calories: 61,
            protein: 1.1,
            carbs: 15,
            fat: 0.5,
        },
        {
            name: "lemon",
            price: 0.4,
            calories: 29,
            protein: 1.1,
            carbs: 9,
            fat: 0.3,
        },
        {
            name: "lime",
            price: 0.3,
            calories: 30,
            protein: 0.7,
            carbs: 10,
            fat: 0.2,
        },
        {
            name: "avocado",
            price: 1.2,
            calories: 160,
            protein: 2,
            carbs: 9,
            fat: 15,
        },
        {
            name: "coconut",
            price: 2.5,
            calories: 354,
            protein: 3.3,
            carbs: 15,
            fat: 33,
        },
        {
            name: "watermelon",
            price: 3.0,
            calories: 30,
            protein: 0.6,
            carbs: 8,
            fat: 0.2,
        },
        {
            name: "cantaloupe",
            price: 2.0,
            calories: 34,
            protein: 0.8,
            carbs: 8,
            fat: 0.2,
        },
        {
            name: "honeydew",
            price: 2.2,
            calories: 36,
            protein: 0.5,
            carbs: 9,
            fat: 0.1,
        },
        {
            name: "plum",
            price: 0.6,
            calories: 46,
            protein: 0.7,
            carbs: 11,
            fat: 0.3,
        },
        {
            name: "apricot",
            price: 0.8,
            calories: 48,
            protein: 1.4,
            carbs: 11,
            fat: 0.4,
        },
    ];

    // Vegetables
    const vegetables = [
        {
            name: "carrot",
            price: 0.2,
            calories: 41,
            protein: 0.9,
            carbs: 10,
            fat: 0.2,
        },
        {
            name: "broccoli",
            price: 1.8,
            calories: 55,
            protein: 3.7,
            carbs: 11,
            fat: 0.6,
        },
        {
            name: "spinach",
            price: 2.0,
            calories: 23,
            protein: 2.9,
            carbs: 3.6,
            fat: 0.4,
        },
        {
            name: "tomato",
            price: 0.8,
            calories: 18,
            protein: 0.9,
            carbs: 3.9,
            fat: 0.2,
        },
        {
            name: "lettuce",
            price: 1.2,
            calories: 15,
            protein: 1.4,
            carbs: 2.9,
            fat: 0.1,
        },
        {
            name: "cucumber",
            price: 0.5,
            calories: 16,
            protein: 0.7,
            carbs: 3.6,
            fat: 0.1,
        },
        {
            name: "bell pepper",
            price: 1.0,
            calories: 31,
            protein: 1,
            carbs: 7,
            fat: 0.3,
        },
        {
            name: "onion",
            price: 0.4,
            calories: 40,
            protein: 1.1,
            carbs: 9,
            fat: 0.1,
        },
        {
            name: "garlic",
            price: 0.3,
            calories: 149,
            protein: 6.4,
            carbs: 33,
            fat: 0.5,
        },
        {
            name: "potato",
            price: 0.6,
            calories: 77,
            protein: 2,
            carbs: 17,
            fat: 0.1,
        },
        {
            name: "sweet potato",
            price: 0.8,
            calories: 86,
            protein: 1.6,
            carbs: 20,
            fat: 0.1,
        },
        {
            name: "cauliflower",
            price: 1.5,
            calories: 25,
            protein: 1.9,
            carbs: 5,
            fat: 0.3,
        },
        {
            name: "asparagus",
            price: 2.5,
            calories: 20,
            protein: 2.2,
            carbs: 3.9,
            fat: 0.1,
        },
        {
            name: "zucchini",
            price: 0.7,
            calories: 17,
            protein: 1.2,
            carbs: 3.1,
            fat: 0.3,
        },
        {
            name: "eggplant",
            price: 1.0,
            calories: 25,
            protein: 1,
            carbs: 6,
            fat: 0.2,
        },
        {
            name: "mushroom",
            price: 1.2,
            calories: 22,
            protein: 3.1,
            carbs: 3.3,
            fat: 0.3,
        },
        {
            name: "corn",
            price: 0.8,
            calories: 86,
            protein: 3.2,
            carbs: 19,
            fat: 1.2,
        },
        {
            name: "peas",
            price: 1.0,
            calories: 84,
            protein: 5.4,
            carbs: 14,
            fat: 0.4,
        },
        {
            name: "green beans",
            price: 0.9,
            calories: 31,
            protein: 1.8,
            carbs: 7,
            fat: 0.2,
        },
        {
            name: "brussels sprouts",
            price: 2.0,
            calories: 43,
            protein: 3.4,
            carbs: 9,
            fat: 0.3,
        },
    ];

    // Dairy & Eggs
    const dairy = [
        {
            name: "milk",
            price: 1.0,
            calories: 42,
            protein: 3.4,
            carbs: 5,
            fat: 1.0,
        },
        {
            name: "cheddar cheese",
            price: 4.0,
            calories: 402,
            protein: 25,
            carbs: 1.3,
            fat: 33,
        },
        {
            name: "mozzarella cheese",
            price: 3.5,
            calories: 280,
            protein: 28,
            carbs: 2.2,
            fat: 17,
        },
        {
            name: "yogurt",
            price: 3.0,
            calories: 59,
            protein: 10,
            carbs: 3.6,
            fat: 0.4,
        },
        {
            name: "butter",
            price: 2.5,
            calories: 717,
            protein: 0.9,
            carbs: 0.1,
            fat: 81,
        },
        {
            name: "egg",
            price: 0.2,
            calories: 155,
            protein: 13,
            carbs: 1.1,
            fat: 11,
        },
        {
            name: "cream cheese",
            price: 2.8,
            calories: 342,
            protein: 6,
            carbs: 4,
            fat: 34,
        },
        {
            name: "cottage cheese",
            price: 2.2,
            calories: 98,
            protein: 11,
            carbs: 3.4,
            fat: 4.3,
        },
        {
            name: "sour cream",
            price: 1.8,
            calories: 193,
            protein: 2.9,
            carbs: 4.3,
            fat: 19,
        },
        {
            name: "heavy cream",
            price: 3.5,
            calories: 340,
            protein: 2.8,
            carbs: 2.8,
            fat: 36,
        },
        {
            name: "parmesan cheese",
            price: 8.0,
            calories: 431,
            protein: 38,
            carbs: 4.1,
            fat: 29,
        },
        {
            name: "feta cheese",
            price: 4.5,
            calories: 264,
            protein: 14,
            carbs: 4.1,
            fat: 21,
        },
        {
            name: "greek yogurt",
            price: 3.5,
            calories: 59,
            protein: 10,
            carbs: 3.6,
            fat: 0.4,
        },
        {
            name: "swiss cheese",
            price: 5.0,
            calories: 380,
            protein: 27,
            carbs: 1.4,
            fat: 28,
        },
        {
            name: "provolone cheese",
            price: 4.2,
            calories: 351,
            protein: 25,
            carbs: 2.1,
            fat: 27,
        },
        {
            name: "blue cheese",
            price: 6.0,
            calories: 353,
            protein: 21,
            carbs: 2.3,
            fat: 29,
        },
        {
            name: "goat cheese",
            price: 5.5,
            calories: 364,
            protein: 22,
            carbs: 0.7,
            fat: 30,
        },
        {
            name: "ricotta cheese",
            price: 3.8,
            calories: 174,
            protein: 11,
            carbs: 3,
            fat: 13,
        },
        {
            name: "brie cheese",
            price: 7.0,
            calories: 334,
            protein: 21,
            carbs: 0.5,
            fat: 28,
        },
        {
            name: "gouda cheese",
            price: 4.8,
            calories: 356,
            protein: 25,
            carbs: 2.2,
            fat: 27,
        },
    ];

    // Meat & Fish
    const meat = [
        {
            name: "chicken breast",
            price: 5.0,
            calories: 165,
            protein: 31,
            carbs: 0,
            fat: 3.6,
        },
        {
            name: "salmon fillet",
            price: 7.5,
            calories: 208,
            protein: 20,
            carbs: 0,
            fat: 13,
        },
        {
            name: "ground beef",
            price: 4.5,
            calories: 250,
            protein: 26,
            carbs: 0,
            fat: 15,
        },
        {
            name: "pork chop",
            price: 4.8,
            calories: 231,
            protein: 26,
            carbs: 0,
            fat: 14,
        },
        {
            name: "turkey breast",
            price: 4.2,
            calories: 157,
            protein: 30,
            carbs: 0,
            fat: 3.6,
        },
        {
            name: "tuna steak",
            price: 6.5,
            calories: 144,
            protein: 30,
            carbs: 0,
            fat: 1,
        },
        {
            name: "lamb chop",
            price: 8.0,
            calories: 294,
            protein: 25,
            carbs: 0,
            fat: 21,
        },
        {
            name: "cod fillet",
            price: 5.5,
            calories: 105,
            protein: 23,
            carbs: 0,
            fat: 0.9,
        },
        {
            name: "shrimp",
            price: 8.5,
            calories: 99,
            protein: 24,
            carbs: 0.2,
            fat: 0.3,
        },
        {
            name: "bacon",
            price: 3.5,
            calories: 541,
            protein: 37,
            carbs: 1.4,
            fat: 42,
        },
        {
            name: "sausage",
            price: 3.8,
            calories: 296,
            protein: 12,
            carbs: 2.1,
            fat: 26,
        },
        {
            name: "ham",
            price: 4.0,
            calories: 145,
            protein: 21,
            carbs: 0.5,
            fat: 6.5,
        },
        {
            name: "tilapia fillet",
            price: 4.2,
            calories: 96,
            protein: 20,
            carbs: 0,
            fat: 2.3,
        },
        {
            name: "beef steak",
            price: 9.0,
            calories: 271,
            protein: 26,
            carbs: 0,
            fat: 18,
        },
        {
            name: "duck breast",
            price: 7.8,
            calories: 337,
            protein: 19,
            carbs: 0,
            fat: 28,
        },
        {
            name: "veal cutlet",
            price: 6.5,
            calories: 172,
            protein: 31,
            carbs: 0,
            fat: 4.8,
        },
        {
            name: "mahi mahi",
            price: 6.8,
            calories: 168,
            protein: 27,
            carbs: 0,
            fat: 6.3,
        },
        {
            name: "scallops",
            price: 9.5,
            calories: 88,
            protein: 17,
            carbs: 2.4,
            fat: 0.8,
        },
        {
            name: "crab meat",
            price: 10.0,
            calories: 97,
            protein: 20,
            carbs: 0.1,
            fat: 1.5,
        },
        {
            name: "lobster tail",
            price: 15.0,
            calories: 89,
            protein: 19,
            carbs: 0.5,
            fat: 0.5,
        },
    ];

    // Grains & Bread
    const grains = [
        {
            name: "bread",
            price: 2.5,
            calories: 265,
            protein: 9,
            carbs: 49,
            fat: 3.2,
        },
        {
            name: "rice",
            price: 1.2,
            calories: 130,
            protein: 2.4,
            carbs: 28,
            fat: 0.3,
        },
        {
            name: "pasta",
            price: 1.5,
            calories: 131,
            protein: 5,
            carbs: 25,
            fat: 1.1,
        },
        {
            name: "quinoa",
            price: 3.0,
            calories: 120,
            protein: 4.4,
            carbs: 22,
            fat: 1.9,
        },
        {
            name: "oatmeal",
            price: 1.8,
            calories: 68,
            protein: 2.4,
            carbs: 12,
            fat: 1.4,
        },
        {
            name: "whole wheat bread",
            price: 3.0,
            calories: 247,
            protein: 13,
            carbs: 41,
            fat: 4.2,
        },
        {
            name: "bagel",
            price: 1.2,
            calories: 245,
            protein: 10,
            carbs: 48,
            fat: 1.5,
        },
        {
            name: "tortilla",
            price: 0.8,
            calories: 146,
            protein: 4.5,
            carbs: 24,
            fat: 3.8,
        },
        {
            name: "english muffin",
            price: 1.0,
            calories: 157,
            protein: 6,
            carbs: 30,
            fat: 1.8,
        },
        {
            name: "croissant",
            price: 1.5,
            calories: 231,
            protein: 5.4,
            carbs: 26,
            fat: 12,
        },
        {
            name: "pita bread",
            price: 1.8,
            calories: 275,
            protein: 9,
            carbs: 56,
            fat: 1.2,
        },
        {
            name: "sourdough bread",
            price: 3.5,
            calories: 289,
            protein: 11,
            carbs: 54,
            fat: 2.2,
        },
        {
            name: "rye bread",
            price: 2.8,
            calories: 259,
            protein: 8.5,
            carbs: 48,
            fat: 3.3,
        },
        {
            name: "cornbread",
            price: 2.0,
            calories: 198,
            protein: 4.5,
            carbs: 33,
            fat: 5.8,
        },
        {
            name: "focaccia",
            price: 3.2,
            calories: 249,
            protein: 8.2,
            carbs: 42,
            fat: 6.8,
        },
        {
            name: "naan bread",
            price: 2.5,
            calories: 262,
            protein: 8.9,
            carbs: 46,
            fat: 4.2,
        },
        {
            name: "challah bread",
            price: 3.8,
            calories: 318,
            protein: 10,
            carbs: 55,
            fat: 7.2,
        },
        {
            name: "ciabatta bread",
            price: 3.0,
            calories: 245,
            protein: 8.5,
            carbs: 47,
            fat: 2.8,
        },
        {
            name: "brioche bread",
            price: 4.0,
            calories: 283,
            protein: 7.5,
            carbs: 45,
            fat: 8.5,
        },
        {
            name: "flatbread",
            price: 2.2,
            calories: 264,
            protein: 8.8,
            carbs: 49,
            fat: 3.8,
        },
    ];

    // Nuts & Seeds
    const nuts = [
        {
            name: "almond",
            price: 15.0,
            calories: 579,
            protein: 21,
            carbs: 22,
            fat: 50,
        },
        {
            name: "walnut",
            price: 12.0,
            calories: 654,
            protein: 15,
            carbs: 14,
            fat: 65,
        },
        {
            name: "cashew",
            price: 14.0,
            calories: 553,
            protein: 18,
            carbs: 30,
            fat: 44,
        },
        {
            name: "peanut",
            price: 8.0,
            calories: 567,
            protein: 26,
            carbs: 16,
            fat: 49,
        },
        {
            name: "pecan",
            price: 16.0,
            calories: 691,
            protein: 9,
            carbs: 14,
            fat: 72,
        },
        {
            name: "pistachio",
            price: 13.0,
            calories: 560,
            protein: 20,
            carbs: 28,
            fat: 45,
        },
        {
            name: "macadamia nut",
            price: 20.0,
            calories: 718,
            protein: 7.9,
            carbs: 14,
            fat: 76,
        },
        {
            name: "hazelnut",
            price: 11.0,
            calories: 628,
            protein: 15,
            carbs: 17,
            fat: 61,
        },
        {
            name: "brazil nut",
            price: 12.0,
            calories: 656,
            protein: 14,
            carbs: 12,
            fat: 66,
        },
        {
            name: "pine nut",
            price: 18.0,
            calories: 673,
            protein: 14,
            carbs: 13,
            fat: 68,
        },
        {
            name: "sunflower seed",
            price: 6.0,
            calories: 584,
            protein: 21,
            carbs: 20,
            fat: 51,
        },
        {
            name: "pumpkin seed",
            price: 7.0,
            calories: 559,
            protein: 19,
            carbs: 54,
            fat: 19,
        },
        {
            name: "chia seed",
            price: 8.0,
            calories: 486,
            protein: 17,
            carbs: 42,
            fat: 31,
        },
        {
            name: "flax seed",
            price: 5.0,
            calories: 534,
            protein: 18,
            carbs: 29,
            fat: 42,
        },
        {
            name: "sesame seed",
            price: 4.0,
            calories: 573,
            protein: 18,
            carbs: 23,
            fat: 50,
        },
        {
            name: "hemp seed",
            price: 9.0,
            calories: 553,
            protein: 31,
            carbs: 9,
            fat: 49,
        },
        {
            name: "poppy seed",
            price: 3.5,
            calories: 525,
            protein: 18,
            carbs: 28,
            fat: 42,
        },
        {
            name: "quinoa seed",
            price: 4.5,
            calories: 120,
            protein: 4.4,
            carbs: 22,
            fat: 1.9,
        },
        {
            name: "amaranth seed",
            price: 5.5,
            calories: 103,
            protein: 4,
            carbs: 19,
            fat: 1.6,
        },
        {
            name: "millet seed",
            price: 3.0,
            calories: 119,
            protein: 3.5,
            carbs: 23,
            fat: 1,
        },
    ];

    // Beverages
    const beverages = [
        {
            name: "orange juice",
            price: 2.5,
            calories: 45,
            protein: 0.7,
            carbs: 10,
            fat: 0.2,
        },
        {
            name: "apple juice",
            price: 2.0,
            calories: 46,
            protein: 0.1,
            carbs: 11,
            fat: 0.1,
        },
        {
            name: "grape juice",
            price: 2.2,
            calories: 62,
            protein: 0.4,
            carbs: 15,
            fat: 0.1,
        },
        {
            name: "cranberry juice",
            price: 2.8,
            calories: 46,
            protein: 0.4,
            carbs: 12,
            fat: 0.1,
        },
        {
            name: "tomato juice",
            price: 1.5,
            calories: 17,
            protein: 0.9,
            carbs: 3.8,
            fat: 0.1,
        },
        {
            name: "lemonade",
            price: 1.8,
            calories: 29,
            protein: 0.2,
            carbs: 7,
            fat: 0.1,
        },
        {
            name: "iced tea",
            price: 1.2,
            calories: 1,
            protein: 0,
            carbs: 0.2,
            fat: 0,
        },
        {
            name: "coffee",
            price: 0.5,
            calories: 2,
            protein: 0.3,
            carbs: 0,
            fat: 0,
        },
        {
            name: "green tea",
            price: 0.8,
            calories: 1,
            protein: 0,
            carbs: 0.2,
            fat: 0,
        },
        {
            name: "hot chocolate",
            price: 2.0,
            calories: 192,
            protein: 8,
            carbs: 25,
            fat: 8,
        },
        {
            name: "almond milk",
            price: 3.5,
            calories: 17,
            protein: 0.6,
            carbs: 0.6,
            fat: 1.5,
        },
        {
            name: "soy milk",
            price: 2.8,
            calories: 33,
            protein: 3.3,
            carbs: 1.8,
            fat: 1.8,
        },
        {
            name: "coconut milk",
            price: 3.0,
            calories: 230,
            protein: 2.3,
            carbs: 6,
            fat: 24,
        },
        {
            name: "oat milk",
            price: 3.2,
            calories: 43,
            protein: 1,
            carbs: 7,
            fat: 1.5,
        },
        {
            name: "rice milk",
            price: 2.5,
            calories: 47,
            protein: 0.3,
            carbs: 9,
            fat: 1,
        },
        {
            name: "energy drink",
            price: 2.5,
            calories: 45,
            protein: 0,
            carbs: 11,
            fat: 0,
        },
        {
            name: "sports drink",
            price: 1.8,
            calories: 21,
            protein: 0,
            carbs: 5,
            fat: 0,
        },
        {
            name: "sparkling water",
            price: 1.0,
            calories: 0,
            protein: 0,
            carbs: 0,
            fat: 0,
        },
        {
            name: "mineral water",
            price: 0.8,
            calories: 0,
            protein: 0,
            carbs: 0,
            fat: 0,
        },
        {
            name: "coconut water",
            price: 2.2,
            calories: 19,
            protein: 0.7,
            carbs: 4,
            fat: 0.2,
        },
    ];

    // Condiments & Sauces
    const condiments = [
        {
            name: "olive oil",
            price: 10.0,
            calories: 884,
            protein: 0,
            carbs: 0,
            fat: 100,
        },
        {
            name: "peanut butter",
            price: 6.0,
            calories: 588,
            protein: 25,
            carbs: 20,
            fat: 50,
        },
        {
            name: "ketchup",
            price: 1.5,
            calories: 102,
            protein: 1.3,
            carbs: 24,
            fat: 0.2,
        },
        {
            name: "mustard",
            price: 1.2,
            calories: 66,
            protein: 4.4,
            carbs: 5.8,
            fat: 4,
        },
        {
            name: "mayonnaise",
            price: 2.0,
            calories: 680,
            protein: 1,
            carbs: 0.6,
            fat: 75,
        },
        {
            name: "soy sauce",
            price: 1.8,
            calories: 60,
            protein: 8,
            carbs: 5.6,
            fat: 0.1,
        },
        {
            name: "hot sauce",
            price: 1.5,
            calories: 6,
            protein: 0.3,
            carbs: 1.3,
            fat: 0.1,
        },
        {
            name: "barbecue sauce",
            price: 2.2,
            calories: 172,
            protein: 0.8,
            carbs: 42,
            fat: 0.2,
        },
        {
            name: "ranch dressing",
            price: 2.5,
            calories: 459,
            protein: 1.3,
            carbs: 2.8,
            fat: 48,
        },
        {
            name: "italian dressing",
            price: 2.0,
            calories: 292,
            protein: 0.3,
            carbs: 2.8,
            fat: 32,
        },
        {
            name: "honey",
            price: 4.0,
            calories: 304,
            protein: 0.3,
            carbs: 82,
            fat: 0,
        },
        {
            name: "maple syrup",
            price: 5.0,
            calories: 260,
            protein: 0,
            carbs: 67,
            fat: 0,
        },
        {
            name: "jam",
            price: 2.8,
            calories: 250,
            protein: 0.3,
            carbs: 65,
            fat: 0.1,
        },
        {
            name: "jelly",
            price: 2.5,
            calories: 250,
            protein: 0,
            carbs: 65,
            fat: 0,
        },
        {
            name: "nutella",
            price: 4.5,
            calories: 539,
            protein: 6.8,
            carbs: 57,
            fat: 30,
        },
        {
            name: "hummus",
            price: 3.5,
            calories: 166,
            protein: 7.9,
            carbs: 14,
            fat: 9.6,
        },
        {
            name: "guacamole",
            price: 4.0,
            calories: 160,
            protein: 2,
            carbs: 9,
            fat: 15,
        },
        {
            name: "salsa",
            price: 2.5,
            calories: 36,
            protein: 1.5,
            carbs: 7,
            fat: 0.2,
        },
        {
            name: "pesto sauce",
            price: 5.0,
            calories: 263,
            protein: 4.3,
            carbs: 4.3,
            fat: 26,
        },
        {
            name: "marinara sauce",
            price: 2.8,
            calories: 74,
            protein: 1.9,
            carbs: 11,
            fat: 2.8,
        },
    ];

    // Snacks & Sweets
    const snacks = [
        {
            name: "chocolate bar",
            price: 2.5,
            calories: 545,
            protein: 4.9,
            carbs: 61,
            fat: 31,
        },
        {
            name: "potato chip",
            price: 3.0,
            calories: 536,
            protein: 7,
            carbs: 53,
            fat: 35,
        },
        {
            name: "popcorn",
            price: 2.0,
            calories: 375,
            protein: 11,
            carbs: 74,
            fat: 4,
        },
        {
            name: "pretzel",
            price: 1.5,
            calories: 380,
            protein: 10,
            carbs: 80,
            fat: 3,
        },
        {
            name: "crackers",
            price: 2.2,
            calories: 502,
            protein: 10,
            carbs: 61,
            fat: 26,
        },
        {
            name: "trail mix",
            price: 4.0,
            calories: 462,
            protein: 14,
            carbs: 45,
            fat: 29,
        },
        {
            name: "granola bar",
            price: 1.8,
            calories: 471,
            protein: 10,
            carbs: 64,
            fat: 20,
        },
        {
            name: "cookies",
            price: 2.5,
            calories: 502,
            protein: 5.7,
            carbs: 65,
            fat: 24,
        },
        {
            name: "ice cream",
            price: 4.5,
            calories: 207,
            protein: 3.5,
            carbs: 24,
            fat: 11,
        },
        {
            name: "yogurt cup",
            price: 1.2,
            calories: 59,
            protein: 10,
            carbs: 3.6,
            fat: 0.4,
        },
        {
            name: "pudding cup",
            price: 1.0,
            calories: 130,
            protein: 2.5,
            carbs: 22,
            fat: 3.5,
        },
        {
            name: "fruit snack",
            price: 1.5,
            calories: 350,
            protein: 0,
            carbs: 87,
            fat: 0,
        },
        {
            name: "cheese stick",
            price: 1.8,
            calories: 80,
            protein: 7,
            carbs: 0.5,
            fat: 6,
        },
        {
            name: "beef jerky",
            price: 3.5,
            calories: 410,
            protein: 33,
            carbs: 11,
            fat: 26,
        },
        {
            name: "protein bar",
            price: 2.8,
            calories: 360,
            protein: 20,
            carbs: 30,
            fat: 12,
        },
        {
            name: "rice cake",
            price: 0.8,
            calories: 35,
            protein: 0.7,
            carbs: 7,
            fat: 0.3,
        },
        {
            name: "corn chip",
            price: 2.2,
            calories: 503,
            protein: 7,
            carbs: 63,
            fat: 26,
        },
        {
            name: "tortilla chip",
            price: 2.0,
            calories: 497,
            protein: 7,
            carbs: 63,
            fat: 24,
        },
        {
            name: "mixed nuts",
            price: 5.0,
            calories: 607,
            protein: 20,
            carbs: 22,
            fat: 54,
        },
        {
            name: "dried fruit",
            price: 3.5,
            calories: 359,
            protein: 3.4,
            carbs: 89,
            fat: 0.5,
        },
    ];

    // Combine all categories
    const allItems = [
        ...fruits,
        ...vegetables,
        ...dairy,
        ...meat,
        ...grains,
        ...nuts,
        ...beverages,
        ...condiments,
        ...snacks,
    ];

    // Generate 200 products with batch numbers and expiry dates
    for (let i = 0; i < 200; i++) {
        const item = allItems[i % allItems.length];
        const batchNumber = `${item.name.substring(0, 3).toUpperCase()}${String(
            i + 1
        ).padStart(3, "0")}`;

        // Generate expiry date (some items don't have expiry dates)
        let expiryDate = null;
        if (
            [
                "milk",
                "yogurt",
                "cheese",
                "egg",
                "meat",
                "fish",
                "bread",
                "juice",
            ].some((type) => item.name.includes(type))
        ) {
            const daysFromNow = Math.floor(Math.random() * 30) + 1; // 1-30 days from now
            expiryDate = new Date();
            expiryDate.setDate(expiryDate.getDate() + daysFromNow);
        }

        // Some items are disabled (out of stock)
        const disabled = Math.random() < 0.05; // 5% chance of being disabled

        products.push({
            name: item.name,
            price: Math.max(0.1, item.price + (Math.random() * 2 - 1) * 0.5), // Ensure price is never negative
            batchNumber: batchNumber,
            expiryDate: expiryDate,
            nutrition: {
                calories: item.calories,
                protein: item.protein,
                carbs: item.carbs,
                fat: item.fat,
            },
            disabled: disabled,
        });
    }

    return products;
};

const sampleItems = generateProducts();

const seedDatabase = async () => {
    try {
        // Connect to MongoDB
        await mongoose.connect(process.env.MONGODB_URI, {
            dbName: "ita602-database",
        });
        console.log("Connected to MongoDB successfully");

        // Clear existing items (optional - comment out if you want to keep existing data)
        await Item.deleteMany({});
        console.log("Cleared existing items");

        // Insert sample items
        const result = await Item.insertMany(sampleItems);
        console.log(
            `Successfully inserted ${result.length} items into the database`
        );

        // Display some sample items
        console.log("\nSample items inserted:");
        result.slice(0, 5).forEach((item) => {
            console.log(`- ${item.name}: $${item.price} (${item.batchNumber})`);
        });

        console.log("\nDatabase seeding completed successfully!");
    } catch (error) {
        console.error("Error seeding database:", error);
    } finally {
        // Close the connection
        await mongoose.connection.close();
        console.log("Database connection closed");
        process.exit(0);
    }
};

// Run the seeding function
seedDatabase();
